# リンターの設定
[ruff]

# 一行あたりの最大文字数をPEP 8の推奨よりも少し緩めに設定
max-line-length = 100

# 特定のエラーコードを無視する設定
ignore = [
  "E203", # コロンの前の空白は、スライスでのみ許可される（blackとの互換性のため）
  "W503", # 行の折り返し演算子の前で改行するべき（PEP 8の更新に基づく）
]

# 特定のファイルやディレクトリを除外する
exclude = [
  "__pycache__",
  "*.pyc",
  "build",
  "dist",
  "*.egg-info",
  ".git",
  ".github",
  "node_modules",
]
